version: '3.8'

services:
  web:
    container_name: local_php
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - local_net

networks:
  local_net:
    name: local_net